return require("migration").define(function()
    migration("Add group_id column to containers for compose group tracking", function()
        database("postgres", function()
            up(function(db)
                db:execute("ALTER TABLE containers ADD COLUMN group_id TEXT")
                db:execute("CREATE INDEX idx_containers_group ON containers(group_id) WHERE group_id IS NOT NULL")
            end)
            down(function(db)
                db:execute("DROP INDEX IF EXISTS idx_containers_group")
                db:execute("ALTER TABLE containers DROP COLUMN group_id")
            end)
        end)
        database("sqlite", function()
            up(function(db)
                db:execute("ALTER TABLE containers ADD COLUMN group_id TEXT")
                db:execute("CREATE INDEX idx_containers_group ON containers(group_id)")
            end)
            down(function(db)
                db:execute("DROP INDEX IF EXISTS idx_containers_group")
            end)
        end)
    end)
end)
