return require("migration").define(function()
    migration("Persist interactive executor identity", function()
        database("postgres", function()
            up(function(db)
                db:execute("ALTER TABLE containers ADD COLUMN executor_route_id TEXT")
                db:execute("ALTER TABLE containers ADD COLUMN executor_id TEXT")
            end)
            down(function(db)
                db:execute("ALTER TABLE containers DROP COLUMN executor_id")
                db:execute("ALTER TABLE containers DROP COLUMN executor_route_id")
            end)
        end)
        database("sqlite", function()
            up(function(db)
                db:execute("ALTER TABLE containers ADD COLUMN executor_route_id TEXT")
                db:execute("ALTER TABLE containers ADD COLUMN executor_id TEXT")
            end)
            down(function(db)
                db:execute("ALTER TABLE containers DROP COLUMN executor_id")
                db:execute("ALTER TABLE containers DROP COLUMN executor_route_id")
            end)
        end)
    end)
end)
