version: "1.0"
namespace: userspace.docker.env

entries:
  - name: database_resource
    kind: env.variable
    meta:
      comment: Database resource for docker storage
      private: true
    default: database
    storage: userspace.docker:os_env
    variable: DOCKER_DB_RESOURCE

  - name: process_host
    kind: env.variable
    meta:
      comment: Process host for docker worker spawning
      private: true
    default: process_host
    storage: userspace.docker:os_env
    variable: DOCKER_PROCESS_HOST
