version: "1.0"
namespace: userspace.docker.persist

entries:
  - name: containers
    kind: library.lua
    source: file://containers.lua
    modules:
      - json
      - sql
      - uuid

  - name: images
    kind: library.lua
    source: file://images.lua
    imports:
      consts: userspace.docker.lib:consts
    modules:
      - json
      - uuid
